development: &defaults
  client_id: 436982539681428
  client_secret: 16522691905b5def08f958a363c4f1dc
  scope: user_about_me,friends_about_me,user_activities,friends_activities,user_groups,friends_groups,user_interests,friends_interests,user_likes,friends_likes,read_friendlists
  canvas_url: http://apps.facebook.com/ifeelfbbypat/

test:
  <<: *defaults

production:
  <<: *defaults